name: ui_bank
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/business-entrepreneur-make-strategy-for-product-and-funding.png
    - assets/images/business-man-illustrate-product-planning-option.png
    - assets/images/back.jpg
    - assets/images/business-product-planning-and-research.png
    - assets/images/business-woman-achieving-the-goal-successfully.png
    - assets/images/cycling.png
    - assets/images/verificado.png